# Generated by Django 4.2.7 on 2023-11-13 22:47

from django.db import migrations, models
import django.db.models.deletion
import st_mvc.base.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=st_mvc.base.base_model.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=st_mvc.base.base_model.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dir', models.CharField(max_length=100, null=True)),
                ('category', models.ManyToManyField(to='st_mvc.category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGames',
            fields=[
                ('id', models.CharField(default=st_mvc.base.base_model.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='mvc_image')),
                ('description', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_mvc.category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreGame',
            fields=[
                ('id', models.CharField(default=st_mvc.base.base_model.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_mvc.videogames')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_mvc.store')),
            ],
            options={
                'db_table': 'store_game',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='games',
            field=models.ManyToManyField(through='st_mvc.StoreGame', to='st_mvc.videogames'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.CharField(default=st_mvc.base.base_model.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('games', models.ManyToManyField(to='st_mvc.videogames')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_mvc.store')),
            ],
            options={
                'db_table': 'video_game',
            },
        ),
    ]
