# Generated by Django 4.2.7 on 2023-11-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_mvc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storegame',
            name='name',
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(blank=True, to='st_mvc.category'),
        ),
    ]
