# Generated by Django 4.2.7 on 2023-11-16 22:25

from django.db import migrations, models
import st_mvc.auxiliar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('st_mvc', '0002_remove_storegame_name_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[st_mvc.auxiliar.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[st_mvc.auxiliar.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[st_mvc.auxiliar.validators.validate_length]),
        ),
        migrations.AlterField(
            model_name='videogames',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[st_mvc.auxiliar.validators.validate_length]),
        ),
    ]
